In [3]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [4]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [5]:
movies = pd.read_csv("Movie+Assignment+Data.csv")
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [6]:
# Write your code for inspection here
print(len(movies.index))
movies.describe()
movies.head()

5043

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [7]:
movies.columns
len(movies.columns)

28

In [8]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [9]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [10]:
# Write your code for column-wise null percentages here
round(100 *(movies.isnull().sum()/len(movies.index)),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [11]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
dropping_columns=["color",'director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords']
movies=movies.drop(dropping_columns,axis=1)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [12]:
# Write your code for dropping the rows here
movies = movies[~np.isnan(movies['gross'])]
movies = movies[~np.isnan(movies['budget'])]

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [13]:
# Write your code for dropping the rows here
movies = movies[movies.isnull().sum(axis=1) <= 5]

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [14]:
movies.loc[:, ['language']].describe()

       language
count      3888
unique       38
top     English
freq       3707

In [15]:
# Write your code for filling the NaN values in the 'language' column here
movies.loc[pd.isnull(movies['language']), ['language']] = 'English'

#np.isnan(movies['language'])
#movies.loc[np.isnan(movies['language']),['language']]

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [16]:
# Write your code for checking number of retained rows here
100*len(movies.index)/5043

77.15645449137418

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [17]:
# Write your code for unit conversion here
movies["budget"]=movies["budget"]/1000000
movies['gross'] =movies['gross']/1000000
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [18]:
# Write your code for creating the profit column here
movies["profit"]= movies['gross'] - movies['budget']

In [19]:
# Write your code for sorting the dataframe here
movies.sort_values("profit",axis=0,ascending=False,inplace=True)

In [20]:
top10 = movies[:9]
print(top10)

         director_name  num_critic_for_reviews       gross  \
0        James Cameron                   723.0  760.505847
29     Colin Trevorrow                   644.0  652.177271
26       James Cameron                   315.0  658.672302
3024      George Lucas                   282.0  460.935665
3080  Steven Spielberg                   215.0  434.949459
794        Joss Whedon                   703.0  623.279547
17         Joss Whedon                   703.0  623.279547
509       Roger Allers                   186.0  422.783777
240       George Lucas                   320.0  474.544677

                                        genres         actor_1_name  \
0              Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29            Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                               Drama|Romance    Leonardo DiCaprio
3024           Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                             Family|Sci-Fi         Henry Thomas
794                    Action|Adventure|Sci-Fi      Chris Hemsworth
17                     Action|Adventure|Sci-Fi      Chris Hemsworth
509   Adventure|Animation|Drama|Family|Musical    Matthew Broderick
240            Action|Adventure|Fantasy|Sci-Fi      Natalie Portman

                                     movie_title  num_voted_users  \
0                                        Avatar            886204
29                               Jurassic World            418214
26                                      Titanic            793059
3024         Star Wars: Episode IV - A New Hope            911097
3080                 E.T. the Extra-Terrestrial            281842
794                                The Avengers            995415
17                                 The Avengers            995415
509                               The Lion King            644348
240   Star Wars: Episode I - The Phantom Menace            534658

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   237.0      2009.0         7.9
29                  1290.0  English   150.0      2015.0         7.0
26                  2528.0  English   200.0      1997.0         7.7
3024                1470.0  English    11.0      1977.0         8.7
3080                 515.0  English    10.5      1982.0         7.9
794                 1722.0  English   220.0      2012.0         8.1
17                  1722.0  English   220.0      2012.0         8.1
509                  656.0  English    45.0      1994.0         8.5
240                 3597.0  English   115.0      1999.0         6.5

      movie_facebook_likes      profit
0                    33000  523.505847
29                  150000  502.177271
26                   26000  458.672302
3024                 33000  449.935665
3080                 34000  424.449459
794                 123000  403.279547
17                  123000  403.279547
509                  17000  377.783777
240                  13000  359.544677

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [21]:
# Write your code for dropping duplicate values here
movies.columns
movies.drop_duplicates(subset=movies.columns,inplace=True)

In [22]:
# Write code for repeating subtask 2 here
top10 = movies[:10]
print(top10)

          director_name  num_critic_for_reviews       gross  \
0         James Cameron                   723.0  760.505847
29      Colin Trevorrow                   644.0  652.177271
26        James Cameron                   315.0  658.672302
3024       George Lucas                   282.0  460.935665
3080   Steven Spielberg                   215.0  434.949459
794         Joss Whedon                   703.0  623.279547
509        Roger Allers                   186.0  422.783777
240        George Lucas                   320.0  474.544677
66    Christopher Nolan                   645.0  533.316061
439           Gary Ross                   673.0  407.999255

                                        genres         actor_1_name  \
0              Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29            Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                               Drama|Romance    Leonardo DiCaprio
3024           Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                             Family|Sci-Fi         Henry Thomas
794                    Action|Adventure|Sci-Fi      Chris Hemsworth
509   Adventure|Animation|Drama|Family|Musical    Matthew Broderick
240            Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
66                 Action|Crime|Drama|Thriller       Christian Bale
439            Adventure|Drama|Sci-Fi|Thriller    Jennifer Lawrence

                                     movie_title  num_voted_users  \
0                                        Avatar            886204
29                               Jurassic World            418214
26                                      Titanic            793059
3024         Star Wars: Episode IV - A New Hope            911097
3080                 E.T. the Extra-Terrestrial            281842
794                                The Avengers            995415
509                               The Lion King            644348
240   Star Wars: Episode I - The Phantom Menace            534658
66                              The Dark Knight           1676169
439                            The Hunger Games            701607

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   237.0      2009.0         7.9
29                  1290.0  English   150.0      2015.0         7.0
26                  2528.0  English   200.0      1997.0         7.7
3024                1470.0  English    11.0      1977.0         8.7
3080                 515.0  English    10.5      1982.0         7.9
794                 1722.0  English   220.0      2012.0         8.1
509                  656.0  English    45.0      1994.0         8.5
240                 3597.0  English   115.0      1999.0         6.5
66                  4667.0  English   185.0      2008.0         9.0
439                 1959.0  English    78.0      2012.0         7.3

      movie_facebook_likes      profit
0                    33000  523.505847
29                  150000  502.177271
26                   26000  458.672302
3024                 33000  449.935665
3080                 34000  424.449459
794                 123000  403.279547
509                  17000  377.783777
240                  13000  359.544677
66                   37000  348.316061
439                 140000  329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [23]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDB_Top_250= movies.loc[movies.num_voted_users>25000,:]
IMDB_Top_250.sort_values("imdb_score",axis=0,ascending=False,inplace=True)
IMDB_Top_250[0:250]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439
283,Ridley Scott,265.0,187.670866,Action|Drama|Romance,Djimon Hounsou,Gladiator,982637,2368.0,English,103.00,2000.0,8.5,21000,84.670866
1571,Francis Ford Coppola,261.0,78.800000,Drama|War,Harrison Ford,Apocalypse Now,450676,983.0,English,31.50,1979.0,8.5,19000,47.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,John Lasseter,191.0,245.823397,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,Toy Story 2,385871,515.0,English,90.00,1999.0,7.9,0,155.823397
1807,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000
3357,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955
2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000
1735,James Mangold,291.0,119.518352,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.00,2005.0,7.9,11000,91.518352
1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.298180
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.505847
3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348
927,Andrew Adamson,212.0,267.652016,Adventure|Animation|Comedy|Family|Fantasy,Kathleen Freeman,Shrek,467113,945.0,English,60.00,2001.0,7.9,0,207.652016
162,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.449459
2449,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.112543
3768,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677
1871,Pierre Morel,309.0,145.000989,Action|Thriller,Liam Neeson,Taken,483756,974.0,English,25.00,2008.0,7.9,29000,120.000989
99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.00,2012.0,7.9,166000,123.001229
4415,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.278739
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354
2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242
2493,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.915039
1748,F. Gary Gray,349.0,161.029270,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.029270
3595,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603
2558,Edgar Wright,285.0,23.618786,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.618786
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783
2492,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000
4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000
639,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.034803
3029,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803

In [24]:
IMDB_Top_250[IMDB_Top_250["language"]!="English"]

Top_Foreign_Lang_Film = IMDB_Top_250[IMDB_Top_250["language"]!="English"]
Top_Foreign_Lang_Film[Top_Foreign_Lang_Film["language"]=="Hindi"]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
3344,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.0000,2010.0,8.0,27000,-7.981305
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.0000,2004.0,7.9,2000,-4.078262
4385,Ritesh Batra,195.0,4.231500,Drama|Romance,Nawazuddin Siddiqui,The Lunchbox,30479,162.0,Hindi,1.0000,2013.0,7.8,16000,3.231500
3276,Yash Chopra,50.0,3.047539,Drama|Romance,Shah Rukh Khan,Jab Tak Hai Jaan,42296,286.0,Hindi,7.2176,2012.0,6.9,12000,-4.170061

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [44]:
# Write your code for extracting the top 10 directors here
grouped=movies.groupby("director_name")
df=grouped["imdb_score"].mean()
sorted=df.sort_values(ascending=False)
sorted.head(10)

director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [91]:
# Write your code for extracting the first two genres of each movie here
new=movies["genres"].str.split("|",n=2,expand=True)
movies["genre_1"]=new[0]
movies["genre_2"]=new[1]
movies.loc[pd.isnull(movies["genre_2"]),"genre_2"]= movies["genre_1"]

pop_group=movies.groupby(["genre_1","genre_2"])
pgdf=pop_group["gross"].mean()
pgdf.sort_values(ascending=False,inplace=True)
pgdf.head(5)

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

SyntaxError: invalid syntax (<ipython-input-86-c3f178da2918>, line 1)

In [93]:
PopGenre = pgdf.head(5)
PopGenre

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [103]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies.loc[(movies.actor_1_name=='Meryl Streep'),:]
Meryl_Streep.shape

(11, 16)

In [104]:
Leo_Caprio =movies.loc[(movies.actor_1_name=='Leonardo DiCaprio'),:]
Leo_Caprio.shape

(21, 16)

In [105]:
Brad_Pitt = movies.loc[(movies.actor_1_name=='Brad Pitt'),:]
Brad_Pitt.shape

(17, 16)

In [112]:
# Write your code for combining the three dataframes here
Combined_1=Meryl_Streep.append(Leo_Caprio)
Combined=Combined_1.append(Brad_Pitt)
Combined.shape

(49, 16)

In [117]:
# Write your code for grouping the combined dataframe here
ga=Combined.groupby("actor_1_name")
ga.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller

In [132]:
# Write the code for finding the mean of critic reviews and audience reviews here
gam=ga["num_critic_for_reviews","num_user_for_reviews"].mean()
gam.sort_values("num_critic_for_reviews",ascending=False)

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      245.000000            742.352941
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!